In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#Set array for one side of grid
points = np.arange(-5,5,0.01)

In [4]:
#Create the grid
dx,dy = np.meshgrid(points,points)

In [10]:
#Shows what one side looks like
dx

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [6]:
dy

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [5]:
# Evaluating Function
z = (np.sin(dx) + np.sin(dy))
z

array([[ 1.91784855e+00,  1.92063718e+00,  1.92332964e+00, ...,
        -8.07710558e-03, -5.48108704e-03, -2.78862876e-03],
       [ 1.92063718e+00,  1.92342581e+00,  1.92611827e+00, ...,
        -5.28847682e-03, -2.69245827e-03, -5.85087534e-14],
       [ 1.92332964e+00,  1.92611827e+00,  1.92881072e+00, ...,
        -2.59601854e-03, -5.63993297e-14,  2.69245827e-03],
       ...,
       [-8.07710558e-03, -5.28847682e-03, -2.59601854e-03, ...,
        -1.93400276e+00, -1.93140674e+00, -1.92871428e+00],
       [-5.48108704e-03, -2.69245827e-03, -5.63993297e-14, ...,
        -1.93140674e+00, -1.92881072e+00, -1.92611827e+00],
       [-2.78862876e-03, -5.85087534e-14,  2.69245827e-03, ...,
        -1.92871428e+00, -1.92611827e+00, -1.92342581e+00]])

In [16]:
#Plot out the second array
plt.imshow(z)
#Plot with a colorbar
plt.colorbar()
#Give the plot a title
plt.title('Plot for sin(x) + sin(y)')

Text(0.5, 1.0, 'Plot for sin(x) + sin(y)')

In [7]:
#Lets learn how to use the numpy where

#First the slow way to do things

A = np.array([1,2,3,4])

B= np.array([100,200,300,400])

#Now a boolean array
condition = np.array([True,True,False,False])

#Using a list comprehension
answer = [(A_val if cond else B_val) for A_val,B_val,cond in zip(A,B,condition)]

#Show the answer
answer

#Problems include speed issues and multi-dimensional array issues

[1, 2, 300, 400]

In [8]:
#Now using numpy.where

answer2 = np.where(condition,A,B)

#Show
answer2

array([  1,   2, 300, 400])

In [22]:
from numpy.random import randn

In [23]:
arr = randn(5,5)
arr

array([[ 0.26192197, -0.89407728,  0.96663103, -0.8738557 ,  1.10547767],
       [-0.02977632,  0.01855352,  0.18557194, -0.58871263,  0.7898536 ],
       [ 0.53742597,  0.26298693,  0.06410004, -2.57365136, -1.30578021],
       [-0.02623939, -0.75700694, -1.43925637, -1.70808296, -1.43320775],
       [ 1.69254045, -0.50385218,  2.39283964,  1.38251016,  0.35220289]])

In [24]:
np.where(arr<0,0,arr)

array([[0.26192197, 0.        , 0.96663103, 0.        , 1.10547767],
       [0.        , 0.01855352, 0.18557194, 0.        , 0.7898536 ],
       [0.53742597, 0.26298693, 0.06410004, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [1.69254045, 0.        , 2.39283964, 1.38251016, 0.35220289]])

In [9]:
#Other Statistical Processing
arr = np.array( [ [1,2,3],[4,5,6],[7,8,9] ] )
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.sum()

45

In [29]:
arr.sum(0)

array([12, 15, 18])

In [30]:
arr.mean()

5.0

In [31]:
arr.std()

2.581988897471611

In [32]:
arr.var()

6.666666666666667

In [33]:
bool_arr = np.array([True,False,True])

In [34]:
bool_arr.any() #return True if any element in the array evaluates to True

True

In [35]:
bool_arr.all() #return True only if all elements in the array evaluates to True

False

In [36]:
#Sort
arr = randn(5)
arr

array([ 0.50341618, -0.4088841 ,  1.04021039, -0.14419844,  0.1645457 ])

In [38]:
arr.sort()
arr

array([-0.4088841 , -0.14419844,  0.1645457 ,  0.50341618,  1.04021039])

In [39]:
countries = np.array(['France','Germany','USA','Russia','USA','Mexico','Germany'])

In [41]:
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')